### ISSUE TITLE
MaizeGDB GO annotations for Jan 2017 Release

### ISSUE THREAD

**Issue by austinmeier** [Planteome/planteome-annotation-data#1]
"We are looking at making a release in December that's before PAG. Therefore please seek MaizeGDB GO annotations especially manual ones now that will go in in this release. This subset should also be deposited by us in GO repositories and thus become a beta tester for GO services."

-PJ

**Comment by jaiswalp** [comment]
@cmungall do you have these GO annotation file.

**Comment by cmungall** [comment]
We have another ticket for this, I think @elserj was assigned?

**Comment by monicacecilia** [comment]
@jaiswalp and @cmungall  I just sent the GAFs from MaizeGDB to both of you.

**Comment by cmungall** [comment]
Yes. Recall we identified syntactic errors with these and proposed a script that would tidy this up and feed back to source. 

@elserj this is the script for validation http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/software/utilities/filter-gene-association.pl?view=log

**Comment by cooperl09** [comment]
Both files are currently on the SVN (http://palea.cgrb.oregonstate.edu/viewsvn/associations/go-associations/) and loaded on dev.

I think it's a bit odd as the 'go_genemodel_MaizeGDB.assoc' file are all listed as proteins not gene_models- I think this is incorrect
Compare with 'po_anatomy_gene_model_zea_MaizeGDB.assoc' or 'po_gene_model_li_Zea_POC.assoc'

**Comment by cooperl09** [comment]
In the 'go_gene_MaizeGDB.assoc' the links out to MaizeGDB reference page is incorrectly formatted: MGDB_REF:3133112
It should be: MaizeGDB_REF:3133112

**Comment by elserj** [comment]
> In the 'go_gene_MaizeGDB.assoc' the links out to MaizeGDB reference page is incorrectly formatted: MGDB_REF:3133112
It should be: MaizeGDB_REF:3133112

Fixed in svn.

**Comment by cooperl09** [comment]
In the 'go_gene_model_MaizeGDB.assoc' file, the links out to MaizeGDB reference page are incorrectly formatted: 
example: MaizeGDB:13376 should be MaizeGDB_REF:13376
See: http://dev.planteome.org/amigo/gene_product/MaizeGDB:12359

**Comment by elserj** [comment]
These seem to be all fixed up and loading without issues.
