### ISSUE TITLE
lentil germplasm traits mapping

### ISSUE THREAD

**Issue by cooperl09** [Planteome/planteome-annotation-data#11]
Annotations on ‘seed shattering’ (TO:0000930):  
8641 lentil germplasm traits mapped to it→ move to new term **legume fruit shattering** (TO:0001074)
Should be from file: to_germplasm_L.culinaris_GRIN.assoc

**Comment by cooperl09** [comment]
Have these been fixed?

**Comment by austinmeier** [comment]
yup!
