### ISSUE TITLE
Links to IRIS database not working in germplasm annotations

### ISSUE THREAD

**Issue by cooperl09** [Planteome/planteome-annotation-data#12]
The links to the germplasm source for these annotations are not working.  
They appear to be from: to_germplasm_O.sativa_IRRI3K.assoc

for example from this page: http://browser.planteome.org/amigo/gene_product/IRIC:IRIS_313-8922
http://oryzasnp.org/iric-portal/_variety.zul?irisid=IRIS_313-8922
And: 
http://browser.planteome.org/amigo/gene_product/IRIC:IRIS_313-8994
http://oryzasnp.org/iric-portal/_variety.zul?irisid=IRIS_313-8994 

etc

**Comment by austinmeier** [comment]
After digging around IRRI's site, and links, I cannot seem to find a URL that corresponds to individual varieties' pages.  I have contacted Jeffery Detras from IRRI to see if he has an answer to this.

**Comment by austinmeier** [comment]
Jeffery replied to my request, and gave me the correct URL formatting for these links.  I have updated the db_xrefs.yaml file to reflect this change:  
https://github.com/Planteome/go-site-xrefs-fork/commit/2b44d9d24e22afa2bcdfcfc7bf05bc911a19e0df
