### ISSUE TITLE
Missing species name- Zea diploperennis

### ISSUE THREAD

**Issue by cooperl09** [Planteome/planteome-annotation-data#13]
There are 24 germplasm TO annotations to the germplasm Ames 13503- http://browser.planteome.org/amigo/gene_product/GRIN:1063789
These are just labeled "Zea" but should be Zea diploperennis- 
See: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=4576

**Comment by austinmeier** [comment]
Fixed.  Should be reflected in the next annotation reload.
