### ISSUE TITLE
sorghum QTL Mappings

### ISSUE THREAD

**Issue by cooperl09** [Planteome/planteome-annotation-data#15]
Request from @jaiswalp: 
Can we get these mappings quickly by the end of this week for sorghum QTL data:
Supplementary Data Set 1 of the [Jiao et al (2016)](http://www.plantcell.org/content/28/7/1551) paper, 13 phenotypes in Supplementary Table 2 of the [Brenton et al (2016)](http://www.genetics.org/content/204/1/21) paper, plant height and 5 height-component phenotypes in the [Brown et al (2008)](http://www.genetics.org/content/180/1/629.long) paper (also used in the [Morris et al](https://www.pnas.org/content/110/2/453), which also scores inflorescence branch length phenotypes in Supplementary Table 2).

And contact Sorghum QTL atlas http://aussorgm.org.au/sorghum-qtl-atlas/for a list of traits they have along with the mapping to TO and CO

**Comment by marcelakarey** [comment]
Hi Laurel, I just wanted to get an updated on this or know whether there is anything additional that you need from us. Thanks much and Happy New Year!

**Comment by cooperl09** [comment]
Yes, this is mostly completed for the papers listed above.  You can find the mappings here: https://docs.google.com/spreadsheets/d/1OzX03D9AhuvH9qK4w1Ru3cB3v5VuMSzLg2BFUUn_zvw/edit?usp=sharing
I received the list of traits from Sorghum Atlas folks just before the holidays.  We are still working on that list.
