### ISSUE TITLE
Systemic issue in GAF file formatting

### ISSUE THREAD

**Issue by serenalotreck** [Planteome/planteome-annotation-data#28]
I'm trying to read in a large quantity of files from the [SVN Repository](http://palea.cgrb.oregonstate.edu/viewsvn/associations/) using the `GafReader` tool from the [goatools](https://github.com/tanghaibao/goatools) library, which requires files to be valid GAF files. 

In the process of doing so, I've identified 3 repeating issues in the `.assoc` files from the repository that prevent them from being read in with goatools' `GafReader`, due to them being violations of [the GAF format](http://geneontology.org/docs/go-annotation-file-gaf-format-2.1):
1. **Misformatted date**: Date is formatted as MMDDYYY instead of the [required YYYYMMDD](http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/#date-column-14)
2. **Non-valid Aspect codes**: The Aspect column has a capital letter different than [P, F or C](http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/#aspect-column-9)
3. **Missing columns**: Even though some of the columns are optional, they still need to be included as empty columns in order for the file to be correctly parsed, and several files  have been missing one or more columns. [This issue](https://github.com/tanghaibao/goatools/issues/195) on goatools' repo describes why all the fields need to be present, even if empty. 

Given that I was only working with a preliminary subset of 45 files, I'm concerned that this issue is quite extensive. I can provide the names of specific files as needed, but as I'm hoping to incorporate most of the database into my pipeline, I suspect the list of problematic files will keep getting longer, and I'm not sure what the best way to deal with that is. If you could let me know how I can best help you fix the issue, that would be great!

**Comment by elserj** [comment]
Should be fixed now. That file was 15 years old and no one had noticed that they didn't appear correctly on our site either, so thanks again for noticing and getting me to fix it.

**Comment by serenalotreck** [comment]
Thank you, glad to help!
