### ISSUE TITLE
Links to RAP-DB broken

### ISSUE THREAD

**Issue by cooperl09** [Planteome/planteome-annotation-data#36]
For example see this rice gene: Os07g0638300
https://browser.planteome.org/amigo/gene_product/RAP-DB:Os07g0638300

It should link to: https://rapdb.dna.affrc.go.jp/locus/?name=Os07g0638300

**Comment by cooperl09** [comment]
I ran across this issue again today.  Here's another example:
https://browser.planteome.org/amigo/gene_product/RAP-DB:Os01g0248900
It should link to: https://rapdb.dna.affrc.go.jp/locus/?name=Os01g0248900

**Comment by elserj** [comment]
Fixed in https://github.com/Planteome/go-site-xrefs-fork/commit/081c717da4935c576fe4b96267b9d5bf9bde90d4 and applied on live site.
