### ISSUE TITLE
Formats of the association files in our database- not all are GAF 2.0

### ISSUE THREAD

**Issue by cooperl09** [Planteome/planteome-annotation-data#6]
@elserj  and I have been looking into the formats of the association files in our database- not all are GAF 2.0. 
Of the 195 assoc files we have in svn (not including ones in test directories), 33 of them are not labeled as gaf-version: 2.0.  One is 2.1  So, there are 31 files that we have to be updated to 2.0.
@elserj  could you post the list?

**Comment by elserj** [comment]
eo-associations/eo_gene_Oryza_Gramene.assoc
eo-associations/eo_protein_Oryza_Gramene.assoc
eo-associations/eo_qtl_Oryza_Gramene.assoc
go-associations/go_geneproduct_Prunus_persica_GDR.assoc
po-associations/po_anatomy_gene_oryza_gramene.assoc
po-associations/po_anatomy_gene_physcomitrella_gramene.assoc
po-associations/po_anatomy_gene_Picea_jaiswallab.assoc
po-associations/po_anatomy_germplasm_Arabidopsis_NASC.assoc
po-associations/po_anatomy_protein_Gossypium_AgBase.assoc
po-associations/po_anatomy_qtl_oryza_gramene.assoc
po-associations/po_gene_Arabidopsis_PPPP.assoc
po-associations/po_gene_G.max_PPPP.assoc
po-associations/po_gene_M.truncatula_PPPP.assoc
po-associations/po_gene_S.lycopersicum_PPPP.assoc
po-associations/po_gene_Z.mays_PPPP.assoc
po-associations/po_germplasm_S.chmielewskii_sgn.assoc
po-associations/po_germplasm_S.lycopersicum_sgn.assoc
po-associations/po_germplasm_S.melongena_sgn.assoc
po-associations/po_germplasm_S.pennellii_sgn.assoc
po-associations/po_growth_gene_oryza_gramene.assoc
po-associations/po_growth_protein_Gossypium_AgBase.assoc
po-associations/po_growth_qtl_oryza_gramene.assoc
po-associations/po_qtl_glycine_SoyBase.assoc
to-associations/to_gene_G.max_PPPP.assoc
to-associations/to_gene_M.truncatula_PPPP.assoc
to-associations/to_gene_Oryza_Gramene.assoc
to-associations/to_gene_O.sativa_PPPP.assoc
to-associations/to_gene_S.lycopersicum_PPPP.assoc
to-associations/to_gene_Z.mays_PPPP.assoc
to-associations/to_protein_Oryza_Gramene.assoc
to-associations/to_qtl_Gramene.assoc

**Comment by elserj** [comment]
This was done on Aug 4 with svn revstion 835.  Must have forgot to close the ticket.
