### ISSUE TITLE
rename files for consistency: go_iprscan_Mimulus_guttatus.assoc and go_ortholog_gene_Mimulus_guttatus_planteome.assoc?

### ISSUE THREAD

**Issue by cooperl09** [Planteome/planteome-annotation-data#7]
These file appears to be mis-named: 
go_iprscan_Mimulus_guttatus.assoc and go_ortholog_gene_Mimulus_guttatus_planteome.assoc

That species does not show up in the list, the taxon id refers to Erythranthe guttata. Mimulus guttatus is a synonym

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=4155

Suggest renaming: 
go_iprscan_Erythranthe_guttata.assoc and go_ortholog_gene_Erythranthe_guttata_planteome.assoc

**Comment by elserj** [comment]
Done in svn rev:878.
